config/routes.rb
Rails.application.routes.draw do
  root 'search_terms#index'
  resources :search_terms, only: [:index]
  resources :searches, only: [:create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :search_term
end

app/models/search_term.rb
class SearchTerm < ApplicationRecord
  has_many :searches, dependent: :destroy

  validates :content, presence: true, allow_blank: false, :uniqueness => { :case_sensitive => false } 

  before_save :downcase_content

  scope :by_terms, -> { order(:content) }
  scope :by_date, -> { order('updated_at DESC') }
  scope :by_count, -> { select('search_terms.*').joins(:searches).group(:id).order('count(search_terms.id) desc') }

  def self.sort_by(params)
    case params
    when 'date'
      SearchTerm.by_date
    when 'terms'
      SearchTerm.by_terms
    when 'count'
      SearchTerm.by_count
    else
      SearchTerm.by_date
    end
  end

  private

  def downcase_content
    self.content = self.content.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/search_terms_controller.rb
class SearchTermsController < ApplicationController
  def index
    @search_terms = SearchTerm.sort_by(params[:order]).paginate(page: params[:page], per_page: 30)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search = Search.find(params[:id])
    @gifs = Giphy.new.search(@search.search_term.content)
    if @gifs.empty?
      flash[:danger] = 'No Gifs Found'
      redirect_to search_terms_path
    end
  rescue ActiveRecord::RecordNotFound => e
    flash[:danger] = e.to_s
    redirect_to search_terms_path
  end

  def create
    search_term = SearchTerm.find_or_create_by!(content: params[:content])
    @search = search_term.searches.create
    search_term.touch
    redirect_to search_path(@search)
  rescue ActiveRecord::RecordInvalid => e
    flash[:danger] = e.to_s
    redirect_to search_terms_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_terms_helper.rb
module SearchTermsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="row content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/search_terms/_search_term.html.erb
<li class='nav-item'>
  <%= form_tag(searches_path) do %>
    <%= hidden_field_tag(:content, search_term.content) %>
    <%= submit_tag("#{search_term.content.titleize} (#{search_term.searches.count})", { class: 'search-link' }) %>
  <% end %>
</li>

app/views/search_terms/index.html.erb
<div class="col-sm-3 sidenav">
  <h4>Giphy Search</h4>
  <%= form_tag(search_terms_path, method: :get) do %>
    <div class='input-group'>
      <%= select_tag(:order, options_for_select([['Date', 'date'], ['Terms', 'terms'], ['Count', 'count']], params[:order]), { class: 'form-control' }) %>
      <%= submit_tag('Sort', { class: 'btn btn-primary' }) %>
    </div>
  <% end %>
  <ul class="nav nav-pills flex-column">
    <% @search_terms.each do |search_term| %>
      <%= render partial: 'search_term', locals: { search_term: search_term } %>
    <% end %>
    <%= will_paginate @search_terms %>
  </ul><br>
</div>

<div class="col-sm-9">
  <h4><small>Search Gifs</small></h4>
  <%= render partial: 'searches/form' %>
</div>

app/views/searches/_form.html.erb
<%= form_tag(searches_path) do %>
  <div class='input-group'>
    <%= text_field_tag(:content, '', { class: 'form-control' }) %>
    <%= submit_tag('Search', { class: 'btn btn-primary' }) %>
  </div>
<% end %>

app/views/searches/_gif.html.erb
<div class='col-sm-6 card'>
  <iframe src=<%= gif.embed_url %> class="giphy-embed" allowFullScreen></iframe><p><a href=<%= gif.url%></a></p>
</div>

app/views/searches/show.html.erb
<div class="col-sm-3 sidenav">
  <h4>Giphy Search</h4>
  <%= link_to "back", search_terms_path, { class: 'btn btn-primary' } %>
  <ul class="nav nav-pills flex-column">
    <% @search.search_term.searches.order('created_at DESC').each do |search| %>
      <li>
        <%= search.created_at.strftime('%m/%d/%y at %I:%M %p') %>
      </li>
    <% end %>
  </ul><br>
</div>

<div class="col-sm-9">
  <h4><small>Search Gifs</small></h4>
  <%= render partial: 'searches/form' %>
  <ul>
    <% @gifs.each_slice(2) do |batch| %>
      <div class='row'>
        <% batch.each do |gif| %>
          <%= render partial: 'gif', locals: { gif: gif } %>
        <% end %>
      </div>
    <% end %>
  <ul>
</div>